config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/recipes/top_rated' => 'recipes#top_rated'

  resources :reviews, except: [:destroy]
  resources :recipe_ingredients
  resources :recipes do
    resources :recipe_ingredients, only: [:new]
    resources :reviews, only: [:new, :index]
  end

  resources :users, except: [:destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  # accepts_nested_attributes_for :ingredient, reject_if: proc { |attributes| attributes['name'].blank? }

  validates :quantity, presence: true

  def ingredient_attributes=(ingredient_attributes)
  	self.ingredient = Ingredient.find_or_create_by(ingredient_attributes) if !ingredient_attributes['name'].blank?
  end
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
	before_action :find_recipe_ingredient, only: [:edit, :update, :destroy]

	def new
		if @recipe = Recipe.find_by(id: params[:recipe_id])
			@recipe_ingredient = @recipe.recipe_ingredients.build
			@recipe_ingredient.build_ingredient		
		end
	end
		

	def create
		# raise params.inspect
		@recipe_ingredient = RecipeIngredient.new(recipe_ingredient_params)	
		# binding.pry
		if @recipe_ingredient.save
			flash[:message] = "Sucessfully added ingredient. Add more or GO BACK!"
			redirect_to new_recipe_recipe_ingredient_path(@recipe_ingredient.recipe)
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @recipe_ingredient.update(recipe_ingredient_params)
			flash[:message] = "Successfully updated Recipe"
			redirect_to recipe_path(@recipe_ingredient.recipe)
		else
			render :edit
		end
	end

	def destroy		
		@recipe_ingredient.delete

		redirect_to recipe_path(@recipe_ingredient.recipe)
	end

	private

	def recipe_ingredient_params
		params.require(:recipe_ingredient).permit(:quantity, :recipe_id, :ingredient_id, ingredient_attributes: [:name])
	end

	def find_recipe_ingredient
		@recipe_ingredient = RecipeIngredient.find_by(id: params[:id])
	end
	
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/views/recipe_ingredients/_form.html.erb

<%= form_for @recipe_ingredient do |f|%>
  <div class="form-group mb-3">
    <%= f.label :ingredient_id, "Select an ingredient  " %><br>
    <%= f.collection_select :ingredient_id, Ingredient.all, :id, :name, include_blank: "Select" %>        
  </div>

  <div class="form-group mb-3">
    <%= f.fields_for :ingredient do |i| %>
      <%= i.label :name, "Or create a new one:  " %><br>
      <%= i.text_field :name %>
    <% end %>
  </div>

  <div class="form-group mb-3">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  

  <%= f.hidden_field :recipe_id %>  

  <%= f.submit class: "btn btn-dark" %>

<% end %>



app/views/recipe_ingredients/_recipe_ingredients.html.erb
<div class="col">
	
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Quantity</th>
					<th>Ingredient</th>

					<% if recipe.user == current_user %>
						<th>Edit Ingredient</th>
					<% end %>
				</tr>
			</thead>

			
			<tbody>
				<% recipe.recipe_ingredients.each do |i| %>
					<tr>
						<td><%= i.quantity %></td>
						<td><%= i.ingredient.name %></td>

						<% if recipe.user == current_user %>
							<td>
								<span class="edit-ingredient">
									<%= link_to "Edit", edit_recipe_ingredient_path(i) %>
								</span>	

								<span class="edit-ingredient">
									<%= link_to "Delete", recipe_ingredient_path(i), data: {:confirm => 'Are you sure?'}, :method => :delete %>
								</span>			
							</td>					
						<% end %>	
					</tr>
				<% end %>
			</tbody>	
		</table>		
</div>

app/views/recipe_ingredients/edit.html.erb
<div class="container form mt-5">
  <%= render partial: 'layouts/errors', locals: {object: @recipe_ingredient} %>
  
  <div class="row">
    <div class="col">
      <h1>Edit Ingredients</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/recipe_ingredients/new.html.erb
<div class="container mt-5 form">
  <%= render partial: 'layouts/errors', locals: {object: @recipe_ingredient} %>

  <div class="row">
    <div class="col">
      <h1>Add Ingredients</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= render 'form' %>
    </div>
  </div>
  
  <div class="row">
    <div class="col">
      <%= link_to "Back to Recipe", recipe_path(@recipe_ingredient.recipe), class: "btn btn-dark" %>
    </div>
  </div>
</div>




