config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/recipes/top_rated' => 'recipes#top_rated'

  resources :reviews, except: [:destroy]
  resources :recipe_ingredients
  resources :recipes do
    resources :recipe_ingredients, only: [:new]
    resources :reviews, only: [:new, :index]
  end

  resources :users, except: [:destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :reviews, dependent: :destroy
	has_many :users, through: :reviews
	belongs_to :user
	has_many :recipe_ingredients, dependent: :destroy
	has_many :ingredients, through: :recipe_ingredients
	has_one_attached :image

	validates :title, presence: true, length: { maximum: 20 }
	validates :cook_time, presence: true
	validates :instructions, presence: true
	validate :is_title_case
	before_validation :make_title_case

	scope :top_rated, -> { left_joins(:reviews).group(:id).order('avg(stars) desc').limit(8) }
	scope :by_user, ->(user_id) { where(user: user_id) }


	def self.by_ingredient(ingredient_id)
		joins(:recipe_ingredients).where("recipe_ingredients.ingredient_id =?", ingredient_id)
	end

	def self.by_recipe_title(title)
		where("title ILIKE ?", "%#{title}%")
	end

	def avg_rating
		Recipe.joins(:reviews).where("reviews.recipe_id =?", self.id).average(:stars).to_i
	end

	def empty_stars
		5 - avg_rating
	end

	private

	def is_title_case
		if title.split.any?{|w|w[0].upcase != w[0]}
			errors.add(:title, "Title must be in title case")
		end
	end

	def make_title_case
		self.title = self.title.titlecase
	end
end
  

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]

	def index
		if !params[:user].blank?
			@recipes = Recipe.by_user(params[:user])
		elsif 
			!params[:ingredient].blank?
			@recipes = Recipe.by_ingredient(params[:ingredient])
		elsif
			!params[:title].blank?
			@recipes = Recipe.by_recipe_title(params[:title])
		else
			@recipes = Recipe.all
		end
	end

	def top_rated
		@recipes = Recipe.top_rated	
		render :index
	end

	def show
	end

	def new
		@recipe = Recipe.new			
	end

	def create
		@recipe = current_user.recipes.build(recipe_params)
		if @recipe.save
			# @recipe.image.purge
			# @recipe.image.attach(params[:ice_cream][:image])
			flash[:message] = "Successfully created Recipe"
			redirect_to recipe_path(@recipe)
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
			flash[:message] = "Successfully updated Recipe"
			redirect_to recipe_path(@recipe)
		else
			render :new
		end
		
	end

	def destroy
		@recipe.destroy

		redirect_to recipes_path
	end

	private

	def recipe_params
		params.require(:recipe).permit(:title, :cook_time, :instructions, :image)			
	end

	def find_recipe
		@recipe = Recipe.find_by(id: params[:id])
	end

end

app/helpers/recipes_helper.rb
module RecipesHelper

  def submitted_on(recipe)
    recipe.created_at.strftime("on %A, %b %e")
  end

end

app/views/recipes/_display_rating.html.erb
<div>
  <% if recipe.reviews.exists? %>	

    <% recipe.avg_rating.times do %>
      <i class="fas fa-star fa-xs stars"></i>
    <% end %>
   
  <% else %>

    <span class="reviews-count"><%= pluralize(recipe.reviews.count, "review") %></span>
    
  <% end %>	
</div>

app/views/recipes/_edit_recipe_buttons.html.erb
<% if @recipe.user == current_user %>
  <div class="col">
    <%= link_to "Add Ingredients", new_recipe_recipe_ingredient_path(@recipe), class: "btn btn-dark" %>
    <%= link_to "Edit Recipe", edit_recipe_path(@recipe), class: "btn btn-dark" %>
    <%= link_to "Delete Recipe", recipe_path(@recipe), data: {:confirm => 'Are you sure?'}, class: "btn btn-dark", method: :delete %>
  </div>
<% end %>

app/views/recipes/_filter_form.html.erb
<%= form_tag("/recipes", method: "get") do %>
	<div class="row">
		<div class="col-lg-3">
				<%= label_tag :user, "Member Name" %>
				<%= select_tag :user, options_from_collection_for_select(User.all, :id, :name), include_blank: true, class: "form-control" %>
		</div>

		<div class="col-lg-3">
				<%= label_tag :ingredient %>
				<%= select_tag :ingredient, options_from_collection_for_select(Ingredient.all, :id, :name), include_blank: true, class: "form-control" %>
		</div>

		<div class="col-lg-3">
				<%= label_tag :title, "Recipe Name" %>
				<%= text_field_tag :title, nil, class: "form-control" %>
		</div>

		<div class="col-lg-3 mt-2">
			<%= submit_tag "Filter", class: "btn btn-dark filter-btn" %>				
		</div>
	</div>
<% end %>

app/views/recipes/_form.html.erb
<div class="container mt-5 form">
	<%= render partial: 'layouts/errors', locals: {object: @recipe} %>

	<div class="row">
			<div class="col text-center fs-3 mb-3">
				<% if @recipe.id %>
					<h3>Edit Recipe</h3>
				<% else %>
					<h3>Add New Recipe</h3>
				<% end %>
			</div>
	</div>

	<%= form_for @recipe do |f| %>
		<div class="row">
			<div class="col">
				<div class="form-group mb-3">
					<%= f.label :title %>
					<%= f.text_field :title, class: "form-control" %>
				</div>

				<div class="form-group mb-3">
					<%= f.label :cook_time, "Enter Cook Time in minutes" %><br>
					<%= f.text_field :cook_time %>
				</div>

				<div class="form-group mb-3">
					<%= f.label :instructions %>
					<%= f.text_area :instructions, class: "form-control" %>
				</div>

				<div class="form-group mb-3">
					<%= f.label :image, class: "mb-1" %><br>
					<%= f.file_field :image %>
				</div>	

				<%= f.submit class: "btn btn-dark" %>
				</div>
			</div>
	<% end %>

	<div class="row">
		<div class="col">
			<%= link_to "Back", recipes_path, class: "btn btn-dark" %>
		</div>
	</div>

</div>





app/views/recipes/_image_and_user.html.erb
<div class="col-md-4">
  <h2><%= recipe.title %> </h2>
    
  <% if recipe.image.attached? %>    
   <%= image_tag url_for(recipe.image), class: "img-thumbnail recipe-show-image" %>
  <% end %>
  <br>
  <small class="recipe-title-content mt-1">
    <b>By:</b> <%= recipe.user.name %> <%= submitted_on recipe %>  
  </small>				
</div>

app/views/recipes/_instructions_and_rating.html.erb
<div class="col-md-8">
  <div class="mt-5">
    <%= render partial: 'display_rating', locals: {recipe: recipe} %>
    <p><small><b>Cook time: </b><%= recipe.cook_time %></small></p>

    <h3>Instructions</h3>
    <div class="instructions">
      <p><%= recipe.instructions %></p>
    </div>				
  </div>

  
  <div>
    
    <%= link_to "Add a Review", new_recipe_review_path(@recipe), class: "btn btn-dark" %>
    
    <%= link_to "See all Reviews", recipe_reviews_path(@recipe), class: "btn btn-dark" %>
  </div>		
</div>

app/views/recipes/_title_and_rating.html.erb
<div class="col-md-8">
  <div class="mt-5">
    <p><small><b>Cook time: </b><%= recipe.cook_time %></small></p>

    <h3>Instructions</h3>
    <div class="instructions">
      <p><%= recipe.instructions %></p>
    </div>				
  </div>

  
  <div>
    
    <%= link_to "Add a Review", new_recipe_review_path(@recipe), class: "btn btn-dark" %>
    
    <%= link_to "See all Reviews", recipe_reviews_path(@recipe), class: "btn btn-dark" %>
  </div>		
</div>

app/views/recipes/edit.html.erb

<%= render 'form' %>

<%= link_to "Back", recipe_path(@recipe), class: "btn btn-primary" %>

app/views/recipes/index.html.erb
<div class="container mt-5">
	<div class="row">
		<div class="col">
			<h5>Filter Recipes by one of the following:</h5>
		</div>

		<%= render 'filter_form' %>
	</div>

	<div class="row mt-3">
		<% @recipes.each do |recipe| %>

			<div class="col-md-6 col-lg-4 col-xl-3 mt-3 text-center">
				<div class="card recipe-card" style="width: 18rem;">
					<% if recipe.image.attached? %>
						<a href="<%= recipe_path(recipe) %>"><%= image_tag url_for(recipe.image), class: "card-img-top", alt: "recipe image", height: "250px" %></a>		
					<% end %>
					<div class="card-body">
						<h5 class="card-title"><%=link_to recipe.title, recipe_path(recipe.id) %></h5>
						<p class="card-text">
							<b><%= render partial: 'display_rating', locals: {recipe: recipe} %></b>

							<small class="recipe-title-content">
								<b>By:</b> <%= recipe.user.name %> <%= submitted_on recipe %>
							</small>	

							<p>
								<small class="recipe-title-content"><b>Ready in</b> - <%= recipe.cook_time %></small>				
							</p>
						</p>
						<a href="<%= recipe_path(recipe) %>" class="btn btn-light recipe-btn">Go to Recipe</a>
					</div>
				</div>
			</div>	
		<% end %>
	</div>
</div>

app/views/recipes/new.html.erb

<%= render 'form' %>


app/views/recipes/show.html.erb
<div class="container mb-5">

	<div class="row">
		<%= render partial: 'image_and_user', locals: {recipe: @recipe} %>

		<%= render partial: 'instructions_and_rating', locals: {recipe: @recipe} %>		
	</div>

	<div class="row mt-3"><%= render 'edit_recipe_buttons' %></div>


	<div class="row mt-3">
		<%= render partial: 'recipe_ingredients/recipe_ingredients', locals: {recipe: @recipe} %>
	</div>

</div>














	








