config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/recipes/top_rated' => 'recipes#top_rated'

  resources :reviews, except: [:destroy]
  resources :recipe_ingredients
  resources :recipes do
    resources :recipe_ingredients, only: [:new]
    resources :reviews, only: [:new, :index]
  end

  resources :users, except: [:destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
	<div class="row text-center">
		<div class="col" id="error-explanation">
			<h2>
				<%= pluralize(object.errors.count, "error") %>
				prohibited this object from being saved:
			</h2>

			<ul>
				<% object.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Recipes", recipes_path, class: "navbar-brand me-5", id: "logo" %>
    

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Top Rated Recipes", recipes_top_rated_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add a Recipe", new_recipe_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "All Reviews", reviews_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add a Review", new_review_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Profile", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="/signup">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/f6ad6df9d4.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
   
    <div class="container mt-2">
      <div class="row text-center">
        <div class="col">
          <% if flash[:error] %>
            <p class="error"><%= flash[:error] %></p>
          <% end %>

          <% if flash[:message] %>
            <p class="message"><%= flash[:message] %></p>
          <% end %>
        </div>
      </div>
    </div>

   
    <div class="mb-5"><%= yield %></div>
   

    
 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </body>

</html>

app/views/layouts/recipes_index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render partial: 'layouts/navbar' %>

    <div class="wrapper">

      <% if flash[:error] %>
        <p class="error"><%= flash[:error] %></p>
      <% end %>

      <% if flash[:message] %>
        <p class="message"><%= flash[:message] %></p>
      <% end %>

    

        <%= yield %>

      

      <footer class="branding">
        <small>&copy; 2021 <strong>Recipes</strong></small>
      </footer>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </body>

</html>